#+TITLE: Emacs-lisp Packaging Tips
* 谁应该读这个文档
刚刚从写 Emacs configure 转到写 emacs package 的同学建议读一下
这个文档。
* Configure 和 package 有什么区别
从 Emacs-lisp 语言角度来说，两者没有多大的区别，可能写 package 的时候，
Emacs-lisp 语言应用的更加规范一点。

但编写 configure 和编写 package 需要遵循的理念有很大的不同：
1. Configure 是写给自己用的，如果其他同学使用你的 configure 出了问题，
   那么他只能自认倒霉，你可以不负任何责任。
2. Package 编写出来主要是给其他人使用的，如果出了问题，维护者是有直接
   责任的:-)

* package 编写原则
1. 成本效益原则：
   1. 编写的 package 不能含有恶意代码，不能窃取用户隐私。
   2. 编写的 package 值得用户花时间和精力去学习使用，谨慎的重复制造轮子。
2. 正确使用 Emacs-lisp
3. 尊重社区惯例原则：主要是代码缩进。
4. 尊重用户选择原则：
   1. 不能随意覆盖自己的用户接口变量
   2. 不能随意覆盖其他 package 的任何全局变量，
      包含用户接口变量和内部使用全局变量。

* 花一些时间给 package 取一个好名字。
Emacs-lisp 和其他 lisp 不同，Emacs-lisp 的全局变量的作用范围非常大，
只要一个 package 加载了，那么在任何地方，都可以访问和设置这个 package
的所有全局变量。

为了防止变量冲突， Emacs 社区有这么一个惯例： 一个 package 的
全局变量，函数定义以及宏定义等，都应该使用统一的前缀，比如：
company 使用 "company-" 前缀。

另外三条建议是：
1. package 不能取其他 package 正在使用或者曾经使用过的名字。
2. package 的名字要好记好写好认，最好是 *一个* 单词或者 *一个* 缩写，
   比如：company, elpa 。
3. package 使用的前缀最好就是 package 的名字。

* 定义变量的正确方式
Emacs-lisp 有许多定义变量的方法，但下面几种是最最常用的。

1. 定义一个用户接口变量
   #+BEGIN_SRC emacs-lisp
   (defcustom elptips-name "elptips-name"
     "Elptips's name.")
   #+END_SRC
2. 定义一个普通的全局变量
   #+BEGIN_SRC emacs-lisp
   (defvar elptips-name "elptips-name"
     "Elptips's name.")
   #+END_SRC
3. 定义一个局部变量
   #+BEGIN_SRC emacs-lisp
   (let ((a 1)
         (b 2)
         c)
     (+ a b))
   #+END_SRC

   #+BEGIN_SRC emacs-lisp
   (let* ((a 1)
          (b 2)
          (c (+ a b)))
     c)
   #+END_SRC

* 变量赋值的正确方式
简单来说，变量必须先被定义，才能对其赋值，这个规则非常简单，
但新手往往不太注意。

在 Emacs-lisp 中，最常用的变量赋值操作符是：setq,
这个操作符是 *变量赋值* 操作符，不是 *变量定义* 操作符。

在一个 package 中，一般只能出现下面 *两种* 赋值结构：
1. 对一个 package *内部使用* 的全局变量进行赋值：
   #+BEGIN_SRC emacs-lisp
   (defvar elptips--name "elptips-name"
     "Elptips's name.")
   (setq elptips--name "elptips-name2")
   #+END_SRC
   注：Emacs-lisp 有一个惯例：使用 "--" 来表示这个全局变量是包内部
   使用的变量，用户不应该使用它，维护者不会维护内部全局变量的兼容性。
2. 对一个局部变量进行赋值：
   #+BEGIN_SRC emacs-lisp
   (let ((a 1)
         (b 2)
         c)
     (setq c (+ a b)))
   #+END_SRC

其他形式的赋值结构都是有问题的：

1. 在 package 中对一个用户接口变量进行赋值，无论这个用户接口变量
   属于自己 package 还是其他 package，比如：
   #+BEGIN_SRC emacs-lisp
   (defcustom elptips-name "elptips-name"
     "Elptips's name.")
   (setq elptips-name "elptips-name2")
   #+END_SRC
   这个赋值直接违反了 “尊重用户选择” 原则，在一定条件下，加载 package 会覆盖
   用户的设置，比如：
   #+BEGIN_SRC emacs-lisp
   (setq elptips-name "elptips-name3")
   (require 'elptips)
   #+END_SRC
2. 不能直接使用 setq 来定义变量
   setq 是变量赋值操作符，但如果被赋值的变量不存在，它会首先定义这个 *全局变量*,
   然后再赋值，编写 configure 的时候，我们经常这样用，但编写 package 的时候，再
   这么用就有问题了。

   下面两个例子是等价的：

   #+BEGIN_SRC emacs-lisp
   (setq elptips-name "elptips-name2")
   #+END_SRC

   #+BEGIN_SRC emacs-lisp
   (defvar elptips-name nil) ;这个全局变量会被用户当成用户接口变量
   (setq elptips-name "elptips-name2")
   #+END_SRC

3. 对一个局部变量赋值之前，没有定义这个局部变量
   #+BEGIN_SRC emacs-lisp
   (let ((a 1)
         (b 2))
     (setq c (+ a b)))
   #+END_SRC

   这个例子本质是定义并赋值了一个 *全局变量* c,
   正确的写法是：

   #+BEGIN_SRC emacs-lisp
   (let ((a 1)
         (b 2)
         c) ; c 不能遗漏
     (setq c (+ a b)))
   #+END_SRC

   由于这种方式很容易出现遗漏，而且出现的问题严重（容易覆盖 Emacs-lisp
   核心使用的全局变量），所以常用 let* 来处理类似情况。

   #+BEGIN_SRC emacs-lisp
   (let* ((a 1)
          (b 2)
          (c (+ a b)))
     c)
   #+END_SRC

* 对变量赋值的再思考
通过讨论 “变量赋值的正确方式”，我们可以发现，在编写 package 的
时候，setq 最合理使用的方式只有 *一种* ： 对 package 内部保留的
全局变量再赋值，也就是：
#+BEGIN_SRC emacs-lisp
(defvar elptips--name "elptips-name"
  "Elptips's name.")
(setq elptips--name "elptips-name2")
#+END_SRC

对局部变量赋值时要慎用 setq, 优先考虑使用 let* , 如果必须使用 setq
对一个局部变量赋值，一定要确保这个局部变量已经在 let 结构中定义了。

在其他情况使用 setq 可能就是滥用了。。。。
* 未完待续。。。
* 尾注

# Local Variables:
# coding: utf-8-unix
# End:
